### PR TITLE
Translations of Text Strings -- translation studies course

### PR DESCRIPTION
**Pull request by balicea**
## Description
_Please provide a summary of the pull request and the issue it fixes. Please add necessary details, context, dependencies, explanation of when review is needed (see next section), etc._

This pull request includes foreign language translation of the text strings in Spanish, Chinese, and Portuguese. These Chinese translations were prepared by a human expert, and replace the machine translations that currently exist. The Spanish translations are updated from the previous translations. There are also some small improvements on the English text strings. An additional pull request will be made once these translations pass a professional review, but this could take months.

[comment]: See Issue #759 for more information.

## Review Time Estimate
_Please give your idea of how soon this pull request needs to be reviewed by selecting one of the options below. This can be based on the criticality of the issue at hand and/or other relevant factors._

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Immediately
- [ ] Within a week
- [ x ] When possible

## Type of changes
_Please select a relevant option:_

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ x ] Other (any another change that does not fall in one of the above categories.)

## Checklist:
_Please select all applicable options:_

[comment]: # (To select your options, please put an 'x' in the all boxes that apply.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ x ] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [ ] I have updated the [CHANGELOG](../CHANGELOG.md).
- [ x ] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [ x ] I have performed a self-review of my own code.
- [ x ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [ x ] My changes generate no new warnings.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

---

[comment]: # (Template credit: This pull request template is based on Embedded Artistry {https://github.com/embeddedartistry/templates/blob/master/.github/PULL_REQUEST_TEMPLATE.md}, Clowder {https://github.com/clowder-framework/clowder/blob/develop/.github/PULL_REQUEST_TEMPLATE.md}, and TalAter {https://github.com/TalAter/open-source-templates} templates.)

### CODE REVIEW

**Review by mihail-varbanov — CHANGES_REQUESTED** [review]
Please preserve the order of the language JSON entries the same across all translations. Please preserve the empty lines between the language entries the same across all translations. Please preserve the indent tabs/spaces in front of every language entry. If I compare two language translation files they should be exactly the same except the translated string values at right for each key. The same concept applies for string translations in health.rules.json.

Adding a new supported language requires more work than just adding a new strings.xx.json into assets and a section in the health.rules.json strings. The iOS/Android native sides also contain string entries, the new supported languages need to get defined as supported by the application. More info on what else needs to be done can be found here:
https://github.com/rokwire/safer-illinois-app/pull/628

**Comment by balicea** [comment]
I will address these issues in the next several days. Thank you for your feedback on this.

**Comment by balicea** [comment]
@mihail-varbanov I am in the process of responding to your requests. In terms of support for Portuguese, we were not expecting Portuguese to be supported upon submission, particularly since Safer is being deprecated. 

However, I looked over the pull request @isaac-galvan made earlier this year. Is this something that I should submit as a separate pull request as changes in those four files? Or is this something we need to request from the developers? Should have a revised PR ready soon. Thanks.

**Comment by mihail-varbanov** [comment]
Hi @balicea, If we are not going to support Portuguese localization all you need to do is to preserve the grouping and formatting in strings.nn.json and health.rules.json. When you get ready with this just submit another PR please.

The Portuguese localization requires software update in application configuration and setting (a developer's work) that I do not see the point of doing this in context of the recent depreciation of Safer app.

**Comment by balicea** [comment]
Also, I tried to help user @karacw refresh her fork of Safer Illinois, but she was forced to issue a PR. Her PR is waiting for approval, but she did not fill out the form. She just needs a fork refresh so that we can complete PR #760 Thanks.

**Comment by balicea** [comment]
I have aligned the files in /assets containing text strings to match the original organizational order, in addition to getting all missing translations for additions to the files since the original fork was made. This contribution should include updates to the Spanish and Chinese translations, in addition to a Portuguese translation. At this time, we do not need this to be supported by the developers.

**Pull request closed without merging**
